# Copyright cocotb contributors
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

# generated with mypy's stubgen script

# 该文件只是类型声明
# 真正实现在c++(pygpi/bind.cpp)

from logging import Logger
from typing import Any, Callable

from cocotb.handle import GPIDiscovery

# 向目标模块定义常量
"""
bind.cpp  把gpi端的常量数值赋值到python端 共23个
static int add_module_constants(PyObject *simulator) {
    // Make the GPI constants accessible from the C world
    if (PyModule_AddIntConstant(simulator, "UNKNOWN", GPI_UNKNOWN) < 0 ||
        PyModule_AddIntConstant(simulator, "MEMORY", GPI_MEMORY) < 0 ||
        PyModule_AddIntConstant(simulator, "MODULE", GPI_MODULE) 
"""
DRIVERS: int
ENUM: int
GENARRAY: int
INTEGER: int
LOADS: int
LOGIC: int
LOGIC_ARRAY: int
MEMORY: int
MODULE: int
NETARRAY: int
OBJECTS: int
PACKAGE: int
REAL: int
STRING: int
STRUCTURE: int
PACKED_STRUCTURE: int
UNKNOWN: int
RISING: int
FALLING: int
VALUE_CHANGE: int
RANGE_UP: int
RANGE_DOWN: int
RANGE_NO_DIR: int

# 回调句柄 共4个 
class gpi_cb_hdl: # 对应c++中的GpiCbHdl类 
    def deregister(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# 迭代器句柄
class gpi_iterator_hdl:# 对应c++中的GpiIteratorHdl类
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> gpi_iterator_hdl: ...
    def __next__(self) -> gpi_sim_hdl: ...

# 基础句柄：模拟硬件对象 共23个static PyMethodDef gpi_sim_hdl_methods[] = {
class gpi_sim_hdl:
    def get_const(self) -> bool: ...
    def get_definition_file(self) -> str: ...
    def get_definition_name(self) -> str: ...
    def get_handle_by_index(self, index: int) -> gpi_sim_hdl | None: ...
    def get_handle_by_name(
        self, name: str, discovery_method: GPIDiscovery | None = GPIDiscovery.AUTO
    ) -> gpi_sim_hdl | None: ...
    def get_indexable(self) -> bool: ...
    def get_name_string(self) -> str: ...
    def get_num_elems(self) -> int: ...
    def get_range(self) -> tuple[int, int, int]: ...
    def get_signal_val_binstr(self) -> str: ...
    def get_signal_val_long(self) -> int: ...
    def get_signal_val_real(self) -> float: ...
    def get_signal_val_str(self) -> bytes: ...
    def get_type(self) -> int: ...
    def get_type_string(self) -> str: ...
    def iterate(self, mode: int) -> gpi_iterator_hdl: ...
    def set_signal_val_binstr(self, action: int, value: str) -> None: ...
    def set_signal_val_int(self, action: int, value: int) -> None: ...
    def set_signal_val_real(self, action: int, value: float) -> None: ...
    def set_signal_val_str(self, action: int, value: bytes) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
# 共17个待实现函数
def get_precision() -> int: ...

def get_root_handle(name: str | None) -> gpi_sim_hdl | None: ...

def get_sim_time() -> tuple[int, int]: ...

def get_simulator_product() -> str: ...

def get_simulator_version() -> str: ...

def is_running() -> bool: ...

def set_gpi_log_level(level: int) -> None: ...

def package_iterate() -> gpi_iterator_hdl: ...

def register_nextstep_callback(func: Callable[..., Any], *args: Any) -> gpi_cb_hdl: ...

def register_readonly_callback(func: Callable[..., Any], *args: Any) -> gpi_cb_hdl: ...

def register_rwsynch_callback(func: Callable[..., Any], *args: Any) -> gpi_cb_hdl: ...

def register_timed_callback(
    time: int, func: Callable[..., Any], *args: Any
) -> gpi_cb_hdl: ...

def register_value_change_callback(
    signal: gpi_sim_hdl, func: Callable[..., Any], edge: int, *args: Any
) -> gpi_cb_hdl: ...

def stop_simulator() -> None: ...
# 实现clock_create即可
class cpp_clock:
    def __init__(self, signal: gpi_sim_hdl) -> None: ...
    def start(
        self, period_steps: int, high_steps: int, start_high: bool, set_action: int
    ) -> None: ...
    def stop(self) -> None: ...

def clock_create(hdl: gpi_sim_hdl) -> cpp_clock: ...

def initialize_logger(
    log_func: Callable[[Logger, int, str, int, str, str], None],
    get_logger: Callable[[str], Logger],
) -> None: ...

def set_sim_event_callback(sim_event_callback: Callable[[], object]) -> None: ...
